version: '3.8'

services:
  db:
    image: postgres:12.4
    container_name: ceodosfreela
    restart: always
    ports: 
      - 12400:5432
    environment:
      - POSTGRES_DB=ceodosfreela
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres